
version: 0.2

phases:
  install:
    commands:
      - curl -O https://releases.hashicorp.com/terraform/1.5.0/terraform_1.5.0_linux_amd64.zip
      - unzip terraform_1.5.0_linux_amd64.zip
      - mv terraform /usr/local/bin/
  build:
    commands:
      - echo "Current directory: $(pwd)"
      - echo "Listing files:"
      - ls -la
      - if [ -d "lib" ]; then cd lib; fi
      - terraform init
      - terraform apply -auto-approve
