version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - echo "Starting Terraform Init"
      - terraform init
  build:
    commands:
      - echo "Running Terraform Apply"
      - terraform apply -auto-approve

artifacts:
  files:
    - '**/*'
